travis:
  secure:
    BINSTAR_TOKEN: CWuhbHoTQ8HPbFCUq7VyLsMGHZkb33AeTcnqmZrXxRibZkwSd+ecw9joID4AtBGVZWSvmgClkFGLh9m+9BYBIFn4bolZ5DlZ+MWb/9jr6SXnrUAb5SKjP+Q9K+/jyHD5MRs3WviieNy5/aC9lrTsd2rgVeAk8DTqHnzWBT0KCTKI8AMCQAk8tTeBbHqTjtCeK3wRPu/iNdm7ZZj4hsj+qShGj66t1NIjySQnoDmnd5f1bcqZRh9JPTES61ftbsemwiB2md0q1MjSiFT2cz3zC9fUc9/p9+aQb0mLpPudJ7XpyEFInC3admOXjQHeeW+tip7m8ouLI/uYJ+FWzwdK0IbeYA0wbZ6Ac1Y3JqXnbZ0LA0tFWQWCvZiSDSsNAHrxJ++NG9XAjQrnzQRteGQsP6/XxvZQHg8oroV3RikXBFCEj6CBTbq+NErGG99/3h8SEudC8Ot33dbwgEyCED9xTKITWJcjasHOIYAs0ICoPWAU3P7UXUQSPe+be7n2yTeqkIs2nwhCPpWWAuwPUxArST40vhV+mHahN5KZiFqfSr/f5k6sWYLdepLuy12tT2Xt/HmtlxoXfb6Itgq/FoGEM4eih+wRjjO6t1IiBdkEY0nCSJ932Ca5jzy02GorvdzPai2b6uzAm+9fdpHajIhwrtx9Qp+wTlGACkzI3UITpgY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
